[program:music_nonebot]
directory=/root/projects/music_bot_projects/music_nonebot
command=/bin/bash -lc "/root/projects/music_bot_projects/music_nonebot/start.sh"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/root/projects/music_bot_projects/music_nonebot/logs/music_api.out.log
stderr_logfile=/root/projects/music_bot_projects/music_nonebot/logs/music_api.err.log
environment=HOME="/root",USER="root"